export const predefinedCategories = [
    "News & Media",
    "Technology",
    "Science",
    "Health & Fitness",
    "Business & Finance",
    "Education",
    "Entertainment",
    "Social Media",
    "Travel",
    "Shopping",
    "Food & Cooking",
    "Sports",
    "Art & Design",
    "Personal Development",
    "Productivity & Tools",
    "Reference",
    "Artificial Intelligence",
    "Cryptocurrency & Blockchain",
    "Sustainability & Environment",
    "Mental Health & Wellness",
    "Remote Work & Digital Nomad",
    "Virtual & Augmented Reality",
    "Podcasts & Audio Content",
    "Gaming & Esports",
    "DIY & Crafts",
    "Mindfulness & Meditation",
    "Cybersecurity",
    "Streaming Services",
    "Home Automation & IoT",
    "Fitness Tech",
    "Plant-based Lifestyle",
    "Space Exploration",
    "Renewable Energy",
    "Programming",
    "Web Development",
    "Mobile Development",
    "Data Science",
    "Machine Learning",
    "Movies & TV",
    "Components",
    "Design",
    "Tools",
    "Other"
];
